name: globalkeith
favicon: null
layout_spectrum: 0.4906152505427599
typography_spectrum: 0.9985112647991627
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fefefe'
    - '#c7c7c7'
    - '#272727'
    - '#6e6e6e'
  brandStrength: 1
  lightness: 0.9375
  saturation: 0.875
  rhythmicContrast: 0.75
purpose: []
